# Generated by Django 4.2.4 on 2023-08-17 16:26

import SocialSnap.app_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[SocialSnap.app_auth.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[SocialSnap.app_auth.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[SocialSnap.app_auth.models.validate_username]),
        ),
    ]
