# Generated by Django 4.1.4 on 2023-08-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_user_is_admin_user_profile_picture_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
