# Generated by Django 4.2.4 on 2023-08-11 21:41

import SocialSnap.Site.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('profile_picture', models.ImageField(null=True, upload_to=SocialSnap.Site.models.Profile.profile_picture_path)),
                ('followers', models.ManyToManyField(blank=True, related_name='following_profiles', to='Site.profile')),
                ('following', models.ManyToManyField(blank=True, related_name='followers_profiles', to='Site.profile')),
            ],
        ),
    ]
