# Generated by Django 4.1.4 on 2023-08-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_remove_profile_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, default=0, related_name='following', to='Site.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, default=0, related_name='followers', to='Site.profile'),
        ),
    ]
