# Generated by Django 4.2.4 on 2023-08-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='Site.comment'),
        ),
    ]
