# Generated by Django 4.1.4 on 2023-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='Site.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='Site.profile'),
        ),
    ]
