# Generated by Django 4.1.4 on 2023-08-06 20:39

import SocialSnap.Site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=SocialSnap.Site.models.Profile.profile_picture_path),
        ),
    ]
